test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  
yandex:
  service: S3
  access_key_id: <%= ENV["YANDEX_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["YANDEX_SECRET_ACCESS_KEY"] %>
  region: ru-central1
  bucket: rails-project-assets
  endpoint: https://storage.yandexcloud.net



# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
